### ISSUE TITLE
Auto-generate FFI bindings for Tizen APIs

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#129]
Recently Tim Sneath, the product manager of Dart and Flutter, has ported most of the commonly used Win32 APIs to Dart using Dart FFI: https://github.com/timsneath/win32. (Notice that it's not an official product from the Dart team but his hobby project!)

Apparently the FFI binding generator ([package:ffigen](https://pub.dev/packages/ffigen)) was not used in the project. Instead, [some different technique](https://github.com/timsneath/win32/tree/main/tool) was used to auto-generate Dart bindings from win32metadata. (I haven't looked into the details.)

Maybe a similar thing can be done for the Tizen native APIs. How good will the quality of the generated bindings be in terms of usability? What limitations would be there?

**Comment by bwikbs** [comment]
Um... it's a interesting topic. 
When we first started this project, I remember that we discuss about similar topic with FFI binding generator. And no matter what the answer, Absolutely not  FFI binding generator we think 🌝 
So.. there is a lot of interest in this ``some different technique``.
I can't predict how this topic will go, but... I hope result of this won't be another efl-js stuff. 😆

**Comment by bwikbs** [comment]
As far as I understand this ``some different technique``...
I was hoping for getting a nice way to call Tizen native API with a bit of work, but... It looks a little different from what I expected. 
(Did I go too far? :scream: )
And even if we can't do this right now... It might be worth considering making ``tizenmetadata`` for the future.

**Comment by swift-kim** [comment]
Of course we cannot achieve this for free and we will need to do some "engineering". What blockers do you have in mind?

Also I actually don't know what win32metadata is, but do you think it would be hard to generate and maintain "tizenmetadata"?

**Comment by bwikbs** [comment]
>  What blockers do you have in mind?
Also I actually don't know what win32metadata is, but do you think it would be hard to generate and maintain "tizenmetadata"?

It's hard to say.. because I don't know this well.. 
Just to share my impression regarding this.. :sweat_smile: 
Each step seems to require a lot of effort, but if I had to pick one . It's making ``winmd`` part(Winmd Emitter). win32metadata is (obviously) too windows dependent so we'll have to make a new one. Of course, it may be over soon , but according to my prejudice, this kind of part takes a lot of time.

**Comment by bwikbs** [comment]
@xiaowei-guan Wow! Let me know when something comes up! :+1:

**Comment by xiaowei-guan** [comment]
## [Windows Metadata (WinMD) files](https://docs.microsoft.com/en-us/uwp/winrt-cref/winmd-files)

**Comment by xiaowei-guan** [comment]
##  Windows metadata(WinMD)
 Windows Runtime (WinRT) APIs are described in machine-readable metadata files with the extension .winmd (also known as Windows Metadata). These metadata files are used by tools and language projections in order to enable language projection. The goal of the windows metadata project is to provide a complete description of the Win32 API surface in metadata so that it can be projected to any language in an automated way, improving correctness and minimizing maintenance overhead.

**Comment by xiaowei-guan** [comment]
#### [Dart/winmd](https://github.com/timsneath/winmd)(This package provides a Dart abstraction over Windows metadata files, making it possible to load them and build Dart FFI interop libraries from the results.)
#### [Dart/win32](https://github.com/timsneath/win32) (A package that wraps some of the most common Win32 API calls using FFI to make them accessible to Dart code without requiring a C compiler or the Windows SDK). 

Dart/win32 depend on the  Dart/winmd. 

If we want to auto generate  FFI binging for Tizen APIS like dart/win32, we need provide Tize metadata file like windMD file,

**Comment by swift-kim** [comment]
Thanks for the investigation.

Generating win32metadata-like metadata for Tizen could be pointless since we only need a projection from C to Dart but not other languages. Has anybody tried generating Dart bindings directly from Tizen C headers using [ffigen](https://pub.dev/packages/ffigen)?

**Comment by swift-kim** [comment]
Some progress has been made by @WonyoungChoi. 🎉

@WonyoungChoi Please share the details when the work is done.

**Comment by WonyoungChoi** [comment]
@swift-kim Okay. I'll organize my code a little more and share it.

**Comment by swift-kim** [comment]
We need some detailed documentation for the package including
- how it works,
- how to use,
- any caveats or current limitations, and
- how to build manually from source.
 
The repo's README should be the best place for it.
