### ISSUE TITLE
When will flutter-tizen support building *.wgt?

### ISSUE THREAD

**Issue by iandis** [flutter-tizen/flutter-tizen#145]
Hi I recently made a demo app to be deployed on a Samsung Signage TV. I thought it could run .tpk files but it could not. So is there any alternative to this using flutter-tizen?

**Comment by swift-kim** [comment]
Packaging a Flutter app into .wgt doesn't make sense as it's a web application package format. This project targets running Flutter apps **natively** on Tizen devices without javascript engines.

> I thought it could run .tpk files but it could not.

Probably you couldn't run .tpk on your device because it didn't meet the minimum Tizen version [requirement](https://github.com/flutter-tizen/flutter-tizen#supported-devices) (Tizen 6.0). As far as I know Samsung Signage devices are backed by Tizen 4.0.

**Comment by xuelian-bai** [comment]
What the model number of your TV?

**Comment by iandis** [comment]
Yes it's Tizen 4.0, I just noticed it. So is Tizen Studio currently the only solution to build .wgt? Or is there any workaround for it? I know Xamarin.Forms can also build Tizen apps but it can't build .wgt.
My TV model is KM24A, it's an SSSP TV

**Comment by swift-kim** [comment]
You should contact your dealer first if you wish to develop your own apps for your kiosk device and need any information about the device.

**Comment by iandis** [comment]
Okay, thanks. Last question, if I only need to create a basic web app on Tizen Studio, it wouldn't need any special APIs like B2B API, right? Like showing lists, pictures, and playing video.

**Comment by swift-kim** [comment]
I don't have an answer to your question, unfortunately. What I only heard is that kiosk devices support native and web app development, but not .NET (Xamarin.Forms) app development.

**Comment by iandis** [comment]
Okay, thank you very much
