### ISSUE TITLE
Web backend support

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#245]
Dart supports compiling Dart code into JavaScript code, so we could support converting Flutter web apps into Tizen web applications (WGT).

This will enable several new scenarios such as,
- Writing apps that make use of plugins that are not natively implemented for Tizen (e.g. FlutterFire)
- Running Flutter apps on TV devices running Tizen 5.5 or older
- Adding a UI app on top of another UI app (for DRM content playback or etc.)

| | Native runtime (current) | Web |
|-|-|-|
| **Performance** | Native performance | Bad |
| **Plugin support** | Requires Tizen-specific implementations | Any plugins implemented for web can be used,<br>but Tizen-specific features may not generally be supported |
| **Tizen version limitations** | Requires Tizen 4.0 (watch) or Tizen 6.0 (TV) | Supports Tizen 5.5 or older (TV) |
| **Multi app packaging** | Only UI app + service app is supported | UI app (WGT) + UI app (TPK) may be supported |

I was able to run some Flutter web apps on my watch (SM-R500) successfully.

![Screen_20211011_023911](https://user-images.githubusercontent.com/40190588/136738456-82fdacc7-6336-46a3-9854-eafb812a9c3e.png) ![Screen_20211011_025957](https://user-images.githubusercontent.com/40190588/136738477-b4a875d0-c2f4-46f6-90e1-1ff7e28483c2.png)

What I did:
1. Build a Flutter app for web (`flutter build web --release`)
1. Create a simple Tizen web project in a new directory.
1. Copy build artifacts (`build/web/*`) into the directory.
1. Build the project into WGT and run on a Tizen device.

Known issues:
- It takes over 30 seconds to launch even a simple app. (Only a black screen is displayed, so at first I thought the app failed to load.)
- The hardware back button does nothing when pressed.
- Need to disable service worker manually (it's by default enabled in `index.html` generated by the tool). Flutter service workers cannot be registered due to [this error](https://developer.tizen.org/forums/web-application-development/serviceworker-support).

I literally don't have any experience with Tizen web applications, so could anybody help me get started with analyzing the launching time performance of the apps?

**Comment by m-bialek** [comment]
In logs I noticed the message:
```
I/CHROMIUM( 5042): [INFO:wrt_proxying_url_loader_factory.cc: CreateLoaderAndStart(101)] url : file:///opt/usr/globalapps/6RO1xV3AKB/res/wgt/main.dart.js
E/CHROMIUM( 5042): [ERROR:wrt_proxying_url_loader_factory.cc: ParseURLInternal(23)] request was blocked by WARP
```
To solve this I added the following line to `config.xml`:
```xml
<tizen:content-security-policy>script-src 'self' 'unsafe-eval'</tizen:content-security-policy>
```
After this `main.dart.js` loaded but as it downloads external files from the internet I got another error:
```
I/CHROMIUM(11075): [INFO:CONSOLE: (4015)] "Refused to load the script 'https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
So I modified `config.xml`:
```xml
<access origin="https://unpkg.com" subdomains="true"/>
<tizen:content-security-policy>script-src 'self' https://* 'unsafe-eval'</tizen:content-security-policy>
```
For me it still did not work, but it was probably because of some issues with network:
```
E/CHROMIUM( 3943): [ERROR:url_request_http_job.cc(947)] [NETWORK ERROR] Failing url : https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.js Error code : -137 Error message : net::ERR_NAME_RESOLUTION_FAILED
```
I downloaded https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.js as well as https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.wasm and https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf. Then I placed them in a root directory of the app. I also changed URLs in `main.dart.js`:
- "https://unpkg.com/canvaskit-wasm@0.28.1/bin/" -> "file:///"
- "https://unpkg.com/canvaskit-wasm@0.28.1/bin/canvaskit.js" -> "file:///canvaskit.js"
- "https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf" -> "file:///KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf"

The app now launches on a mobile emulator and my RPi and shows its content instead of a blank screen.

**Comment by m-bialek** [comment]
I assume downloading external files consumes some time. With three files (see comment above) placed in a package, it takes the app under 10s to launch on an emulator and a real device.  It is still quite long, but better than 30s.
