### ISSUE TITLE
Emulator + DevTools

### ISSUE THREAD

**Issue by patrykka** [flutter-tizen/flutter-tizen#280]
Dear All,

I am facing problem with DevTools and tizen emulator.
Everything works fine, Flutter DevTools address is logged in VSC console but when I try to reach it, following information occur:
![flutter](https://user-images.githubusercontent.com/5477159/142674442-5cf72d0a-4f2c-4b23-9947-8ceed0482994.png)
Any suggestions?
Thank you in advance.

**Comment by swift-kim** [comment]
I have no concrete idea about the error but,

1. Which version of the Flutter engine are you using? (`flutter-tizen doctor -v`)
2. Have you tried launching DevTools from the command line (`flutter-tizen pub global run devtools`) instead of using the built-in one? The details can be found here: https://docs.flutter.dev/development/tools/devtools/cli
3. Have you tried attaching to the VM service using the VS Code debugger (with the Flutter extension installed)? You can find the details here: https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/debug-app.md#debugging-in-vs-code

**Comment by patrykka** [comment]
Thank you so much, manual run od devtools works for me.
In field "Connect to a Running App" I put manualy address from flutter-run output.

Thank you for support.

**Comment by swift-kim** [comment]
Sounds great. It isn't still clear what the root cause is but it could a bug in the old version (2.6.0) of DevTools. (The current stable version is 2.8.0. You can find the `devtools.version` file in `flutter-tizen/flutter/bin/internal` and manually modify its value.)

**Comment by patrykka** [comment]
Currently even DevTools 2.6.0 are working but only when I manualy ran them by `flutter-tizen pub global run devtools`.
Thank you for support
