### ISSUE TITLE
fuchsia os support

### ISSUE THREAD

**Issue by lenchis001** [flutter-tizen/flutter-tizen#313]
Hello, everyone!
I've heart that Samsung is planning to move to fuchsia os for all devices (including TVs).

Does anybody know something about it?
Will flutter-tizen native app work on fuchsia os?

**Comment by swift-kim** [comment]
I'm pretty sure that's NOT a fact and I can confirm that Samsung TVs will continue to use Tizen OS.

Even if it's true, your existing app should work on any platform because Flutter is cross-platform (unless the app depends on platform-specific plugins). I don't know if Google will open source and release their Flutter plugins for Fuchsia.
