### ISSUE TITLE
Tizen 6.5 and Flutter

### ISSUE THREAD

**Issue by lenchis001** [flutter-tizen/flutter-tizen#334]
Hello, all!

I've heart that Samsung is planning to support Flutter from Tizen 6.5, not 6.0. Do you know something this decision? What kind of restrictions don't allow to support 6.0?

**Comment by swift-kim** [comment]
As far as I know there's nothing new about Flutter support on Tizen 6.5. We've been supporting Flutter on Tizen since Tizen 4.0 (for watch) and Tizen 6.0 (for TV), and it seems this project was just announced in the [Tizen 6.5 M2 release note](https://docs.tizen.org/platform/what-is-tizen/versions/tizen-6-5-m2) publicly (we're not directly affiliated with the Tizen project team and I was not told about the announcement). I heard that the Tizen SDK team is trying to integrate our Flutter tooling into their product but I don't have details.

**Comment by lenchis001** [comment]
Thanks!
