### ISSUE TITLE
Run app on Tizen Studio

### ISSUE THREAD

**Issue by rafaeliga** [flutter-tizen/flutter-tizen#464]
Hello,

When working with iOS or android, I can run their generated projects on Xcode or Android Studio.

Is that possible for flutter-tizen on Tizen Studio or maybe Visual Studio?

Thanks,

**Comment by swift-kim** [comment]
Hi.

For C++ projects (created with `flutter-tizen create --tizen-language cpp`), no, they cannot be directly launched from **Tizen Studio**.

For C# projects (default), yes, it is technically possible to launch them in **Visual Studio** and debug their **C#** code. (You can't debug their **Dart** code in Visual Studio however.)

1. Install the [Visual Studio Tools for Tizen](https://marketplace.visualstudio.com/items?itemName=tizen.VisualStudioToolsforTizen) extension from the Visual Studio marketplace and set it up properly (go to [Tools]-[Options...]-[Tizen]-[Tools] and configure your Tizen Studio path).
2. Find the `tizen/Runner.csproj` file in your Flutter project and open it in Visual Studio by choosing "Open a project or solution".
3. Build your app at least once from CLI using `flutter-tizen run` so that necessary files (the Flutter engine and compiled Dart code) are generated in the `tizen/flutter/ephemeral` directory.
4. If Visual Studio complains about unresolvable dependencies (`Tizen.Flutter.Embedding`), right click on the solution in the Solution Explorer, choose [Add]-[Existing project...], navigate to your flutter-tizen installation directory and add the `embedding/csharp/Tizen.Flutter.Embedding/Tizen.Flutter.Embedding.csproj` project to the solution.
5. Launch the app (by pressing `F5` or `Ctrl`+`F5`).

![](https://github.com/swift-kim/warehouse/blob/master/images/debug-in-visual-studio.png?raw=true)

If you have any trouble, please let me know.

**Comment by rafaeliga** [comment]
Thank you very much @swift-kim !

Thats exactly was I looking for as I dont have experience with C#/Visual Studio!

I was trying to run my app in a IDE because Im implementing a video player([bitmovin](https://github.com/bitmovin/bitmovin-player-tizen-demo)) in a webview ([lwe](https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter_lwe) / [tizen](https://github.com/flutter-tizen/plugins/tree/master/packages/webview_flutter)), loading a html string, and cant debug anything inside like console.log or js errors...do you have any idea how to try to see those errors?

**Comment by swift-kim** [comment]
@rafaeliga You're welcome. If what you want to debug is not C# code, Visual Studio is not a good choice. I wonder why you're even trying to build your app with Flutter. Why don't you just write a web (.wgt) app and embed a video player inside it?

@bbrto21 @bwikbs Do you know if logging/debugging is available for webviews? (Obviously 3rd-party developers do not have an access to dlog on their TV devices.)

**Comment by rafaeliga** [comment]
@swift-kim The app already has version for iOS/android and android TV. 

My plan was to use the same code / structure that I did for android tv.

When you say to generate a .wgt and use it...do you mean I can embed in a Flutter/Tizen view or just a new tizen web app?

Thanks again!

**Comment by swift-kim** [comment]
Yes, I was referring to a fresh Tizen web app. The webview_flutter_tizen plugin looks still quite unstable and I don't think it's ready for production use.
