### ISSUE TITLE
Add plugin_ffi type support

### ISSUE THREAD

**Issue by WonyoungChoi** [flutter-tizen/flutter-tizen#468]
https://docs.flutter.dev/development/packages-and-plugins/developing-packages#types

It is necessary to add `flutter-tizen` functionalities so that FFI plugin packages can be created and used.

- In plugin_ffi template of flutter, there is no platform-specific native source code and the source code has a `CMakeLists.txt` to make a shared library. 
```
.
├── analysis_options.yaml
├── CHANGELOG.md
├── ffigen.yaml
├── ffitest.iml
├── lib
│   ├── ffitest_bindings_generated.dart
│   └── ffitest.dart
├── LICENSE
├── pubspec.lock
├── pubspec.yaml
├── README.md
└── src
    ├── CMakeLists.txt
    ├── ffitest.c
    └── ffitest.h
```

A lot of questions.
should flutter tizen use this template? Or should we use our own template? Is it possible to build cmake with tizen sdk? Should a single plugin library (libflutter_plugins.so) policy be continued?

**Comment by swift-kim** [comment]
I already considered this once but decided [not to support](https://github.com/flutter-tizen/flutter-tizen/blob/cc54f7c7519b51430651c10edde16833a13bc34c/lib/commands/create.dart#L247-L249) the template because it didn't make much sense for our use cases.

> should flutter tizen use this template?

I don't think so.

> Or should we use our own template?

I don't think it's necessary. It's quite straightforward to write a Dart plugin from scratch without a template.

> Is it possible to build cmake with tizen sdk?

Tizen SDK doesn't support CMake.

> Should a single plugin library (libflutter_plugins.so) policy be continued?

We already support sharedLib type plugins.
