### ISSUE TITLE
GBS build support

### ISSUE THREAD

**Issue by swift-kim** [flutter-tizen/flutter-tizen#469]
Can we build Flutter apps with GBS/QuickBuild?

- Can the flutter-tizen tool and its dependencies be fetched (offline) during the build?
  - .NET CLI and nuget packages
  - Tizen CLI and rootstrap?
  - flutter_tools dependencies (pub packages)
  - Prebuilt engine and embedder artifacts
- Can the apps' dependencies (pub packages) be fetched during the build?
- How to export the build artifacts to the RPM format?

**Comment by WonyoungChoi** [comment]
Why don't you use ABS instead?
If we should build the flutter apps in GBS environment, ...
- .NET CLI and nuget packages : dotnet-build-tools rpm package already provides the dotnet cli but nuget packages should be prepared locally. 
- RPM format: we don't need consider this issue. we can just use `.preload-tpk` directory in the rpm spec file. https://code.sec.samsung.net/confluence/pages/viewpage.action?pageId=295940510
- rootstrap can be resolved with `BuildRequires` in spec files. But we should use make, cmake, gcc directly instead of tizen cli. 
- dart packages and dependencies : we should provide them locally also... 😢

**Comment by swift-kim** [comment]
@WonyoungChoi What is ABS? I can't find on google... is it only for internal developers?

I just heard some VD developers build their apps with GBS/VBS and export to the RPM format. (FYI: The [Lumos](https://github.sec.samsung.net/VD-Evangelist/Lumos) extension for VS Code supports the feature.)

> But we should use make, cmake, gcc directly instead of tizen cli.

This is critical. It means we can't reuse the tool's existing build system (especially the plugin builder) and we'll have to write things from scratch or even need a new architecture.

**Comment by WonyoungChoi** [comment]
As far as I know, SR and DA are using the ABS (App Build System) to build preload applications.  https://code.sec.samsung.net/confluence/display/RSSO/02-01.+Preloaded+APP+Development
In case of VD, we should use GBS environment unfortunately.  :(
I think we need to check again with the SDK part to see if Tizen CLI can be used in the GBS environment.

**Comment by swift-kim** [comment]
a) Support building Flutter apps with GBS:

Not planned.

b) Share `libflutter_engine.so` and `libflutter_tizen.so` between apps:

Instead of embedding the shared libraries into the platform image, consider enabling TAC to share the address space between apps and effectively reduce the memory usage. Note that TAC is currently applied only to `.so` files in the app's `bin` directory, not the `lib` directory. Please contact the .NET runtime team for details.

```xml
<metadata key="http://tizen.org/metadata/prefer_nuget_cache" value="true" />
```
