### ISSUE TITLE
[QUESTION] Why not support flutter "properly"?

### ISSUE THREAD

**Issue by under3415** [flutter-tizen/flutter-tizen#531]
I have an app that has some success on Google TV. I'd love to publish it on Tizen, but half the plugins I use are not supported. I'm sure there are many other developers in the same boat. This is a lose-lose situation!

Why not support flutter instead of forking it? 

You can develop a few plugins that are specific to Samsung (app reviews, in app purchases, ads) and our apps will work on your platform with minimal effort. 

With a fork it will never be as good as the real thing. You cannot compete with Google and their army of volunteers on their home turf.

**Comment by swift-kim** [comment]
I'd say flutter-tizen is a pure port of the Flutter SDK to the Tizen platform rather than a "fork" of it. We haven't touched the Flutter framework and engine code itself. If you're saying we should use the engine and embedder built for (say) Android or Linux GTK as is, that's nonsense. The CPU architecture and everything else is not compatible at all. That's why platform embedders exist. flutter-tizen is no different from Flutter Desktop (for Windows and macOS) and flutter-pi/flutter-elinux (for embedded Linux). They all have their own embedders developed for their platforms. The only difference is that the former (Flutter Desktop) is officially supported and maintained by Google, while other community-driven projects are not. Users of such third-party products should be aware of the difference and the limitations it imposes. Of course, it would be great if Tizen could also get official support from Google, but I don't see that happening in the near future.

I agree that there are still not enough Flutter plugins developed for the Tizen platform. The [in-app purchase plugin](https://pub.dev/packages/in_app_purchase_tizen) for Samsung TV is already available on pub.dev (although it's not mature). If there are other plugins you need, please leave a request and we'll review. If you have any other problems or difficulties during development, please feel free to ask for help by opening an issue.

**Comment by mhoeckner** [comment]
I agree to @swift-kim  - the power of Flutter is to create an own embedder for your SOC/CPU architecture. And this is what the guys do here and a lot of other for their embedded devices. 

What kind of plugins are you missing?  Or are they maybe android specific one?

**Comment by swift-kim** [comment]
These are packages written in pure Dart, not plugins:

- carousel_slider
- encrypt
- flutter_svg
- hive
- hive_flutter
- intl
- json_annotation
- json_serializable
- lottie
- numberpicker
- provider

so they should just work on Tizen.

As for the Firebase-related plugins, we have already ported the FlutterFire plugins that are already ported for the desktop (Windows and macOS) to Tizen, but those two specific ones (analytics and crashlytics) have not yet been ported to the desktop and I'm not sure when they will be available. You have to opt out the features when building your app for Tizen.

These plugins are already implemented for Tizen or at least there are alternatives:

- flutter_local_notifications (tizen_notification)
- in_app_purchase (in_app_purchase_tizen)
- just_audio (audioplayers_tizen)
- path_provider (path_provider_tizen)

Then the rest is as follows:

- app_install_date
- flutter_timezone
- google_mobile_ads
- in_app_review
- wakelock_plus

These have not been ported to Tizen for various reasons (e.g. platform limitations). We can implement a few or provide an alternative if not restricted by the platform (TV). The most critical one would be google_mobile_ads, but it hasn't even been ported to the desktop platforms so it would be a challenge to port it to the Tizen platform, especially without support from Google.

It would be awesome if everything worked like a charm on every platform without much effort, but as I mentioned above, that's impossible. That's the dream of every cross-platform framework. However, if the Android on Tizen project succeeds in the near future, it could hopefully be realized.

**Comment by under3415** [comment]
OK, that's not too bad. What are the options for monetization with Flutter on Tizen if Google ads are not available?

**Comment by swift-kim** [comment]
The most typical scenario for TV apps is that you host a live streaming/VOD service that has a monthly subscription plan (which can be purchased via in-app purchase), or you add pre-roll/mid-roll ads to your videos by integrating a server-side ad insertion technology. The latter is complicated because most multimedia ad servicing SDKs are not available for Flutter and Samsung TV as far as I know. For example, Google's [Dynamic Ad Insertion](https://admanager.google.com/home/resources/feature-brief-dynamic-ad-insertion) client SDK has no Flutter integration. Also I don't know if the video player on TV is VSAT compliant. In fact, I don't have much knowledge in this field.

@haesik @xuelian-bai Do you know anything about this topic?

**Comment by haesik** [comment]
I think Samsung TV has an advertising system that covers above scenarios, but it's not open to 3rd party app developers. In order to open the system, more discussions are needed within Samsung.
