### ISSUE TITLE
Extension for VS Code 

### ISSUE THREAD

**Issue by xuelian-bai** [flutter-tizen/flutter-tizen#88]
This issue is about requirements for vs code extension.

**Comment by xuelian-bai** [comment]
1. Create flutter-tizen project.
2. Debug/Run tizen emulator

**Comment by xiaowei-guan** [comment]
3.Flutter widget inspector
4.Performance view
5.CPU profiler view
6.Memory view
7.Network View
8.Logging view
9.app size tool

**Comment by swift-kim** [comment]
There are several ways to implement the VS Code extension for flutter-tizen:

- Create a fork of the official Flutter extension (https://github.com/Dart-Code/Dart-Code)
- Contribute to the official extension (by somehow integrating flutter-tizen with the extension as an external plugin)
- Create from scratch

Each has its pros and cons, and whichever way you choose, implementing and **maintaining** the extension will be time-consuming and difficult. More importantly, how much benifit can we earn from implementing such an extension for flutter-tizen? flutter-tizen has very limited number of users, and the number of users who want to use advanced debugging features when developing Tizen apps should be even lower. Please note that [flutter-tizen already supports DevTools](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/devtools-usage.md) which comes with a source-level debugger although it's not as usable as a standalone extension for IDEs.

**Comment by swift-kim** [comment]
The development of a dedicated extension for Tizen has been paused after discussion with @xuelian-bai, because the VS Code debugger support has already been added by https://github.com/flutter-tizen/flutter-tizen/pull/196 (See [Debugging apps](https://github.com/flutter-tizen/flutter-tizen/blob/master/doc/debug-app.md) for usage) and the developer experience would not be greatly improved by offering the extension. The decision may be changed if there is high demand from users in the future.
